model:
  base_learning_rate: 4e-06
  target: taming.models.score_enc.Net2NetTransformer
  params:
    transformer_config:
      target: taming.modules.transformer.scores.bert
      params:
        vocab_size: 64
        block_size: 784
        n_layer: 12
        n_head: 8
        n_embd: 256
    first_stage_config:
      target: taming.models.vqgan.VQModel
      params:
        ckpt_path: ../../tf-logs/2023-03-15T21-39-08_class6/check_points/last.ckpt
        embed_dim: 64
        n_embed: 64
        monitor: val/nll_loss
        classname: class6
        ddconfig:
          double_z: False
          z_channels: 128
          resolution: 224
          in_channels: 1
          out_ch: 1
          ch: 32
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 20
    num_workers: 8
    train:
      target: taming.data.new_dataloader.DAGMDataset
      params:
        source: ../DAGM
        classname: class6
        split: train
    validation:
      target: taming.data.new_dataloader.DAGMDataset
      params:
        source: ../DAGM
        classname: class6
        split: test
    test:
      target: taming.data.new_dataloader.DAGMDataset
      params:
        source: ../DAGM
        classname: class6
        split: test